<script>
    $(function() {

        var options = {
            columnsSelector: ".column",
            itemTemplateSelector: "#podTemplate",
            itemClasses: "pod",
            data: [
                {
                    "id": "0",
                    "title": "Apple",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "1",
                    "title": "Plum",
                    "desc": "Leia yoda skywalker chewbacca solo maul binks binks organa. Lando owen naboo amidala kit calrissian lando."
                },
                {
                    "id": "2",
                    "title": "Banana",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "3",
                    "title": "Cherry",
                    "desc": "Dagobah skywalker yavin tatooine c-3po."
                },
                {
                    "id": "4",
                    "title": "Bread",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "5",
                    "title": "Milk",
                    "desc": "Dagobah qui-gon antilles dagobah skywalker yavin tatooine c-3po."
                },
                {
                    "id": "6",
                    "title": "Water",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "7",
                    "title": "Sweet",
                    "desc": "Jednička hlavička je naše jednička"
                },
                {
                    "id": "8",
                    "title": "Bublegum",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "9",
                    "title": "Egg",
                    "desc": "Moje malá nula jedna z mnoha ale krásná, kdo by řekl že je něco jinak tak by se spletl a to hodně"
                },
                {
                    "id": "10",
                    "title": "Toast",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "11",
                    "title": "Tomato",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "12",
                    "title": "Potato",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo."
                },
                {
                    "id": "13",
                    "title": "Rice",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "14",
                    "title": "Mango",
                    "desc": "Leia yoda skywalker chewbacca solo maul binks binks organa. Lando owen naboo amidala kit calrissian lando."
                },
                {
                    "id": "15",
                    "title": "Chockolate",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "16",
                    "title": "Apple",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "17",
                    "title": "Plum",
                    "desc": "Leia yoda skywalker chewbacca solo maul binks binks organa. Lando owen naboo amidala kit calrissian lando."
                },
                {
                    "id": "18",
                    "title": "Banana",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "19",
                    "title": "Cherry",
                    "desc": "Dagobah skywalker yavin tatooine c-3po."
                },
                {
                    "id": "20",
                    "title": "Bread",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "21",
                    "title": "Milk",
                    "desc": "Dagobah qui-gon antilles dagobah skywalker yavin tatooine c-3po."
                },
                {
                    "id": "22",
                    "title": "Water",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "23",
                    "title": "Sweet",
                    "desc": "Jednička hlavička je naše jednička"
                },
                {
                    "id": "24",
                    "title": "Bublegum",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "25",
                    "title": "Egg",
                    "desc": "Moje malá nula jedna z mnoha ale krásná, kdo by řekl že je něco jinak tak by se spletl a to hodně"
                },
                {
                    "id": "26",
                    "title": "Toast",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "27",
                    "title": "Tomato",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "28",
                    "title": "Potato",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo."
                },
                {
                    "id": "29",
                    "title": "Rice",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "30",
                    "title": "Mango",
                    "desc": "Leia yoda skywalker chewbacca solo maul binks binks organa. Lando owen naboo amidala kit calrissian lando."
                },
                {
                    "id": "31",
                    "title": "Chockolate",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "32",
                    "title": "Apple",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "33",
                    "title": "Plum",
                    "desc": "Leia yoda skywalker chewbacca solo maul binks binks organa. Lando owen naboo amidala kit calrissian lando."
                },
                {
                    "id": "34",
                    "title": "Banana",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "35",
                    "title": "Cherry",
                    "desc": "Dagobah skywalker yavin tatooine c-3po."
                },
                {
                    "id": "36",
                    "title": "Bread",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "37",
                    "title": "Milk",
                    "desc": "Dagobah qui-gon antilles dagobah skywalker yavin tatooine c-3po."
                },
                {
                    "id": "38",
                    "title": "Water",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "39",
                    "title": "Sweet",
                    "desc": "Jednička hlavička je naše jednička"
                },
                {
                    "id": "40",
                    "title": "Bublegum",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "41",
                    "title": "Egg",
                    "desc": "Moje malá nula jedna z mnoha ale krásná, kdo by řekl že je něco jinak tak by se spletl a to hodně"
                },
                {
                    "id": "42",
                    "title": "Toast",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "43",
                    "title": "Tomato",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "44",
                    "title": "Potato",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo."
                },
                {
                    "id": "45",
                    "title": "Rice",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "46",
                    "title": "Mango",
                    "desc": "Leia yoda skywalker chewbacca solo maul binks binks organa. Lando owen naboo amidala kit calrissian lando."
                },
                {
                    "id": "47",
                    "title": "Chockolate",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "48",
                    "title": "Apple",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "49",
                    "title": "Plum",
                    "desc": "Leia yoda skywalker chewbacca solo maul binks binks organa. Lando owen naboo amidala kit calrissian lando."
                },
                {
                    "id": "50",
                    "title": "Banana",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "51",
                    "title": "Cherry",
                    "desc": "Dagobah skywalker yavin tatooine c-3po."
                },
                {
                    "id": "52",
                    "title": "Bread",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "53",
                    "title": "Milk",
                    "desc": "Dagobah qui-gon antilles dagobah skywalker yavin tatooine c-3po."
                },
                {
                    "id": "54",
                    "title": "Water",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "55",
                    "title": "Sweet",
                    "desc": "Jednička hlavička je naše jednička"
                },
                {
                    "id": "56",
                    "title": "Bublegum",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "57",
                    "title": "Egg",
                    "desc": "Moje malá nula jedna z mnoha ale krásná, kdo by řekl že je něco jinak tak by se spletl a to hodně"
                },
                {
                    "id": "58",
                    "title": "Toast",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "59",
                    "title": "Tomato",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "60",
                    "title": "Potato",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo."
                },
                {
                    "id": "61",
                    "title": "Rice",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "62",
                    "title": "Mango",
                    "desc": "Leia yoda skywalker chewbacca solo maul binks binks organa. Lando owen naboo amidala kit calrissian lando."
                },
                {
                    "id": "63",
                    "title": "Chockolate",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "64",
                    "title": "Apple",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "65",
                    "title": "Plum",
                    "desc": "Leia yoda skywalker chewbacca solo maul binks binks organa. Lando owen naboo amidala kit calrissian lando."
                },
                {
                    "id": "66",
                    "title": "Banana",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "67",
                    "title": "Cherry",
                    "desc": "Dagobah skywalker yavin tatooine c-3po."
                },
                {
                    "id": "68",
                    "title": "Bread",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "69",
                    "title": "Milk",
                    "desc": "Dagobah qui-gon antilles dagobah skywalker yavin tatooine c-3po."
                },
                {
                    "id": "70",
                    "title": "Water",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "71",
                    "title": "Sweet",
                    "desc": "Jednička hlavička je naše jednička"
                },
                {
                    "id": "72",
                    "title": "Bublegum",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo. Jar grievous jawa mustafar ackbar darth."
                },
                {
                    "id": "73",
                    "title": "Egg",
                    "desc": "Moje malá nula jedna z mnoha ale krásná, kdo by řekl že je něco jinak tak by se spletl a to hodně"
                },
                {
                    "id": "74",
                    "title": "Toast",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "75",
                    "title": "Tomato",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "76",
                    "title": "Potato",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo."
                },
                {
                    "id": "77",
                    "title": "Rice",
                    "desc": "Organa maul jar dagobah."
                },
                {
                    "id": "78",
                    "title": "Mango",
                    "desc": "Leia yoda skywalker chewbacca solo maul binks binks organa. Lando owen naboo amidala kit calrissian lando."
                },
                {
                    "id": "79",
                    "title": "Chockolate",
                    "desc": "Skywalker bespin moff darth solo boba darth."
                },
                {
                    "id": "80",
                    "title": "Coffee",
                    "desc": "Moff skywalker skywalker qui-gon grievous obi-wan lobot hutt greedo."
                }
            ]
        };

        var scrollModel = new ScrollModel({options: options});
        new ScrollView({el: $("#infiniteScrollList"), model: scrollModel, options: options});

    })
</script>

<div class='info'>
    This page works with an offline data only. Check the page source.
    <ul class="links">
        <li><a href='https://github.com/dizzyn/#'>Documentation here</a></li>
    </ul>
</div>

<div id="infiniteScrollList">
    <div class="column column-first"></div>
    <div class="column column-second"></div>
    <div class="column column-third"></div>

    <div class="btn btn-more">Load more</div>
    <div class="state no-more-state">There are no more items</div>
    <div class="state load-state">Loading...</div>

    <script type="text/template" id="podTemplate">
        <h3><%= title %></h3>
        <div class="id"><%= id %></div>
        <div class="desc"><%= desc %></div>
    </script>

</div>

